# Generated by Django 3.0.8 on 2020-07-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('titulo', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateTimeField()),
                ('data_cricao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evento',
            }
        ),
    ]
